### ISSUE TITLE
Migrate the production database to AWS RDS

### ISSUE THREAD

**Issue by ohaiwalt** [OperationCode/operationcode_infra#15]
The production OpCode db is currently in a container in Kubernetes. While this is super neat, it makes things a bit tricky in terms of backups.

Given the level of time that volunteers have to allocate to maintaining the infrastructure, putting the database in AWS RDS greatly reduces the maintenance burden, and will likely be more reliable.

- [x]  Create the RDS database
- [x]  Create a DB backup of the container
- [ ]  Restore the DB backup into the RDS instance

**Comment by ohaiwalt** [comment]
Running into some issues with importing the database backup to the RDS instance, due to lack of superuser permissions.

Initial failures looked like
```
psql:opcode-prod-db.sql:28: ERROR:  must be owner of extension plpgsql
```

After doing a test to remove references to plpgsql from the dump, failures looked like
```
psql:opcode-prod-db.sql:70: ERROR:  must be owner of relation code_schools_id_seq
```

Dump was performed from within postgres container, copied to local, and then restore attempted with the following
```bash
# database container
su - postgres
pg_dump operationcode_production > /tmp/opcode.sql

# retrieved to local machine

# attempting restore
psql -f opcode.sql operationcode_production -h <servername> -U <superuser> -1
```

**Comment by kylemh** [comment]
Database was initially created and managed by `postgres` user. In an attempt to utilize users/roles properly, we we're trying to import the DB on RDS with `opcode_superuser` instead of `postgres`, but had not updated the dump's references to `postgres` user for Table/Relationship ownerships.

Resolution:
Find and replace usages of `postgres` for `opcode_superuser` throughout dumpfile.

Next step:
Issue incoming on the creation and role establishment of an "application user" to safely handle data manipulation without risking schema shape or - god forbid - the entire destruction of our database.
